name: taskfull
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'


dependencies:
  bottom_navy_bar: ^6.0.0
  controller: ^0.1.12
  date_format: ^2.0.7
  flutter:
    sdk: flutter
  flutter_gallery_assets: ^1.0.2
  flutter_riverpod: ^2.5.1
  geolocator: ^11.0.0
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.2.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  path: ^1.9.0
  
  sqflite: ^2.3.3
  supabase_flutter: ^2.4.0
animated_splash_screen:


  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.5.0 
  percent_indicator: ^4.2.3
  date_picker_timeline: ^1.2.5
  intl: ^0.19.0

  sqflite:

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter_riverpod: ^2.3.6
  gap: ^3.0.1
  go_router: ^13.2.4

  uuid:



  flutter_lints: ^3.0.2
  build_runner: ^2.4.9
  hive_generator: ^2.0.1

  


flutter:


  uses-material-design: true

  assets:
    - images/

  